### PR TITLE
Key -value display option

### PR DESCRIPTION
**Pull request by bhalonen**
Another display option that shows the key and the amount of the key. Helps with slightly larger multisets with mulitple components.

### CODE REVIEW

**Comment by scheinerman** [comment]
Hi. Thanks for this. Is there a way I can test this out before I accept and release a new version? (Sorry, I'm really bad at this git stuff.)

**Comment by scheinerman** [comment]
@bhalonen Can you let me know how I can test this before committing to a merge? (Sorry I'm not well-versed in the world of git.) Thanks.

**Comment by bhalonen** [comment]
clone my repo in a fresh project and run ```julia --project``` in it.

git command: ```git clone https://github.com/laurium-labs/Multisets.jl.git```

**Comment by scheinerman** [comment]
Merged. I'll push out a new release.

**Pull request merged**
